blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # Blog
    path('', include('blogs.urls')),
    # Users
    path('users/', include('users.urls')),
]

blog/blogs/urls.py
""" Defines URL's for blogs. """

from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Add a new blog
    path('new_blog/', views.new_blog, name='new_blog'),
    # Edit a blog
    path('edit_blog/<int:blog_id>/' , views.edit_blog, name='edit_blog'),
    # Delete a blog
    path('delete_blog/<int:blog_id>/', views.delete_blog, name='delete_blog'),
]

blog/users/urls.py
""" Defines URLS for blog users. """

from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'
urlpatterns = [
    # Login page
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), 
    name='login'),
    # Logout page
    path('logout/', views.logout_view, name='logout'),
    # Register new account
    path('register/', views.register, name='register'),
]

blog/blogs/models.py
""" Models for blogs. """
from django.db import models
from django.contrib.auth.models import User

class BlogPost(models.Model):
    """ A blog that contains a title, text and the date of entry. """
    title = models.CharField(max_length=50)
    text = models.TextField(max_length=300)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        """ Return a string representation of the model. """
        return self.title

blog/users/models.py
from django.db import models

blog/blogs/forms.py
from django import forms


from .models import BlogPost

class BlogPost(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        labels = {'title': 'Blog Title:', 'text': ''}
        widgets = {'text': forms.Textarea(attrs={'placeholder': 'blog content...', 
        'cols': 50,}), }
        

blog/users/forms.py
from django.contrib.auth.forms import UserCreationForm



class UserCreateForm(UserCreationForm):
    """ Create a user registration form with no help text. """
    
    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None
            

blog/blogs/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from .models import BlogPost
from .forms import BlogPost as BlogPostForm

def index(request):
    """ The home page for blogs also displays all blogs. """
    blog_posts = BlogPost.objects.order_by('date_added')
    context = {'blog_posts': blog_posts}
    return render(request, 'blogs/index.html', context)


@login_required
def new_blog(request):
    """ Create a new blog post. """
    if request.method != 'POST':
        # No data submitted; create a blank form
        form = BlogPostForm()
    else:
        # POST data submitted; process data
        form = BlogPostForm(request.POST)
        if form.is_valid():
            new_blog_post = form.save(commit=False)
            new_blog_post.owner = request.user
            new_blog_post.save()
            return HttpResponseRedirect(reverse('blogs:index'))
    
    context = {'form': form}
    return render(request, 'blogs/new_blog.html', context)


def edit_blog(request, blog_id):
    """ Edit a particular blogs title and text. """
    blog_post = get_object_or_404(BlogPost, id=blog_id)

    if check_user_rights(request, blog_post):
        if request.method != 'POST':
            # Initial request; pre-fill form with current blog info
            form = BlogPostForm(instance=blog_post)
        else:
            # POST data submitted; process data
            form = BlogPostForm(instance=blog_post, data=request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('blogs:index'))
        
        context = {'blog_post': blog_post, 'form': form}
        return render(request, 'blogs/edit_blog.html', context)
    else:
        return HttpResponseRedirect(reverse('blogs:index'))


def delete_blog(request, blog_id):
    """ Deletes selected blog from website. """
    blog_post = get_object_or_404(BlogPost, id=blog_id)

    if check_user_rights(request, blog_post):
        blog_post.delete()

    return HttpResponseRedirect(reverse('blogs:index'))


def check_user_rights(request, blog_post):
    """ Checks if user is a superuser or the owner of blog post.  """
    if request.user == blog_post.owner:
        return True
    elif request.user.is_superuser:
        return True
    else:
        return False

blog/users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import AuthenticationForm

from .forms import UserCreateForm


def logout_view(request):
    """ Logout user. """
    logout(request)
    return HttpResponseRedirect(reverse('blogs:index'))


def register(request):
    """ Register a new user. """
    # Logout user if still logged
    logout(request)
    
    if request.method != 'POST':
        # Display blank registeration form
        form = UserCreateForm()
    else:
        # Process completed form
        form = UserCreateForm(data=request.POST)

    if form.is_valid():
        new_user = form.save()
        # Log the user in and redirect to home page
        authenticated_user = authenticate(username=new_user.username,
            password=request.POST['password1'])
        login(request, authenticated_user)
        return HttpResponseRedirect(reverse('blogs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Font Awsome -->
    <script src="https://kit.fontawesome.com/f1beb0d26f.js" crossorigin="anonymous"></script>
    <!-- CSS -->
    <link rel="stylesheet" href="{% static './css/styles.css' %}">
    <!-- Icon -->
    <link rel="icon" href="{% static './images/thb-logo.png' %}">
    <title>The Hottest Blogs {% block title %}{% endblock title %}</title>
</head>
<body>
    <div class="navbar">
        <ul class="nav-links">
            <li>
                <a href="{% url 'blogs:index' %}">Home</a>
            </li>
        </ul>

        <ul class="nav-logins">
            {% if user.is_authenticated %}
                <li>
                    <a class="greetings">Hello, {{ user.username }}</a>
                </li>
                <li>
                    <a href="{% url 'users:logout' %}" class="logout">log out</a>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'users:login' %}">log in</a>
                </li>
                <li>
                    <a href="{% url 'users:register' %}">register</a>
                </li>
            {% endif %}
        </ul>
    </div>

    <div class="container">
        {% block content %}{% endblock content %}
    </div>
</body>
</html>

blog/templates/blogs/edit_blog.html
{% extends 'base.html' %}

{% block title %}Edit Blog{% endblock title %}
{% block content %}

<div class="title-container-small">
    <h1>Editing {{ blog_post.title }}</h1>
</div>

<div class="blog-items-container">

    <form class="blog-form" action="{% url 'blogs:edit_blog' blog_post.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <div class="blog-items-footer">
            <button class="btn" name="submit">edit blog</button>
        </div>
    </form>
</div>

{% endblock content %}

blog/templates/blogs/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}
{% block content %}

    <div class="title-container">
        <h1>The Hottest Blogs</h1>
    </div>
    
    <div class="blog-items-container">
        {% for blog_post in blog_posts %}

        <div class="blog-item-container">
            <div class="blog-item-header">

                <div class="blog-header-right">
                    <h3>{{ blog_post }}</h3>
                    <p class="blog-timestamp">{{ blog_post.date_added }}</p>
                </div>

                {% if request.user == blog_post.owner or user.is_superuser %}
                    <div class="blog-header-left">
                            <a href="{% url 'blogs:edit_blog' blog_post.id %}"><i class="fas fa-pencil-alt edit"></i></a>
                            <a href="{% url 'blogs:delete_blog' blog_post.id %}"><i class="fas fa-trash delete"></i></a>
                    </div>
                {% endif %}
            </div>
            
            <div class="blog-item-text">
                {{ blog_post.text }}
            </div>
            
        </div>
        
        {% empty %}
        <div class="empty">
            <h3 class="center-text">No posts have been posted yet.</h3>
        </div>
        {% endfor %}

    </div>
    <div class="blog-items-footer">
        <a href="{% url 'blogs:new_blog' %}" class="btn">Create post</a>
    </div>

{% endblock content %}

blog/templates/blogs/new_blog.html
{% extends 'base.html' %}

{% block title %}New Blog{% endblock title %}
{% block content %}

    <div class="title-container-small">
        <h1>Add a new blog</h1>
    </div>

    <div class="blog-items-container">

        <form class="blog-form" action="{% url 'blogs:new_blog' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <div class="blog-items-footer">
                <button class="btn" name="submit">add blog</button>
            </div>
        </form>
    </div>

{% endblock content %}

blog/templates/users/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock title %}
{% block content %}


    <div class="login-container">
        {% if form.errors %}
            <p>Your username and password didn't match. Please try again.</p>
        {% endif %}

        <form action="{% url 'users:login' %}" class="login-form" method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <div class="btn-container">
                <button class="login-btn btn">login</button>
            </div>

            <input type="hidden" name="next" value="{% url 'blogs:index' %}">
        </form>
    </div>

{% endblock content %}

blog/templates/users/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock title %}
{% block content %}

    <div class="login-container">
        <form action="{% url 'users:register' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <div class="btn-container">
                <button class="btn login-btn" name="submit">register</button>
            </div>
            <input type="hidden" name="next" value="{% url 'users:register' %}">
        </form>
    </div>

{% endblock content %}