pizzeria/pizzas/urls.py
""" Handle URL for pizzas app. """

from django.urls import path

from . import views

app_name = 'pizzas'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Show all pizzas
    path('pizza_list/', views.pizza_list, name='pizza_list'),
    # Show individual pizza
    path('pizza_list/<str:pizza_name>/', views.pizza_page, name='pizza_page'),
]

pizzeria/pizzeria/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls'))
]

pizzeria/pizzas/models.py
from django.db import models


class Pizza(models.Model):
    """A topic the user is learning about."""
    name = models.CharField(max_length=30)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.name


class Topping(models.Model):
    """Something specific learned about a topic."""
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Toppings'

    def __str__(self):
        """Return a string representation of the model."""
        return f'{self.name}'

pizzeria/pizzas/views.py
from django.shortcuts import render

from pizzas.models import Pizza, Topping


def index(request):
    """ The homepage for pizzas app. """
    return render(request, 'pizzas/index.html')

def pizza_list(request):
    """ Show all pizzas on the page. """
    pizzas = Pizza.objects.order_by('date_added')
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas.html', context)

def pizza_page(request, pizza_name):
    """ Show a specific pizza and its toppings on the page. """
    pizzas = Pizza.objects.order_by('date_added')
    for p in pizzas:
        if p.name == pizza_name:
            pizza = p 
            break

    toppings = pizza.topping_set.order_by('-date_added')
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas/pizza.html', context)

pizzeria/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- ICON -->
    <link rel="icon" href="{% static './images/pizza.png' %}">
    <!-- CSS -->
    <link rel="stylesheet" href="{% static './css/styles.css' %}">
    <title>Pizzas {% block title %}{% endblock title %}</title>
</head>
<body>
    <div class="nav-bar">
        <div class="nav-header">

                <div class="nav-logo">
                    <a href="{% url 'pizzas:index' %}">
                        <img src="{% static './images/pizza.png' %}" alt="logo">
                    </a>
                </div>
                
                <a href="{% url 'pizzas:index' %}"><h1>Pizzeria</h1></a> 

        </div>


        <ul class="nav-links">
            <li>
                <a href="{% url 'pizzas:index' %}">Home</a>
            </li>
            <li>
                <a href="{% url 'pizzas:pizza_list' %}">Pizzas</a>
            </li>
        </ul>
    </div>

    <div class="container">
        {% block content %}{% endblock content %}
    </div>

</body>
</html>

pizzeria/templates/pizzas/index.html
{% extends 'base.html' %}

{% block title %} Home {% endblock title %}
{%  block content %}

	<div class="list-container">

		<div class="list-title center-text">
			<h1>Welcome to the Pizzas homepage!</h1>
		</div>
	</div>

{%  endblock content %}

pizzeria/templates/pizzas/pizza.html
{% extends 'base.html' %}

{% block title %} {{ pizza }} {% endblock title %}
{% block content %}

    <div class="list-container">
        <div class="list-title">
            <h1>Toppings in {{ pizza }}:</h1>
        </div>
        <ul class="list-items">
            {% for topping in toppings %}
                <li class="list-item">
                    <p>{{ topping }}</p>
                </li>
            {% empty %}
                <li class="list-item">
                   <p>No toppings availabe.</p>
                </li>
            {% endfor %}
        </ul>
    </div>
    
{% endblock content %}

pizzeria/templates/pizzas/pizzas.html
{% extends 'base.html' %}

{% block title %} List {% endblock title %}
{% block content %}

    <div class="list-container">
        <div class="list-title">
            <h1>Here are all the pizzas</h1>
        </div>
        
        <ul class="list-items">
            {% for pizza in pizzas %}
            <li class="list-item">
                <a href="{% url 'pizzas:pizza_page' pizza.name %}">{{ pizza }}</a>
            </li>
            {% empty %}
            <li class="list-item">
                <p>No pizzas have been added yet.</p>
            </li>
            {% endfor %}
        </ul>
    </div>

{% endblock content %}